default_url_options:
  host: 'https://namikki.herokuapp.com/'
config.action_mailer.delivery_method = :smtp
config.action_mailer.smtp_settings = {
  address:              'smtp.gmail.com',
  port:                 587,
  domain:               'example.com',
  user_name:            Rails.application.credentials.gmail[:user_name],
  password:             Rails.applicetion.credentials.gmail[:password],
  authentication:       'plain',
  enable_starttls_auto: true }

